"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DESTROY_PAGE_ACTION = exports.REQUEST_PASSWORD_RESET_FAILED_ACTION = exports.REQUEST_PASSWORD_RESET_SUCCESS_ACTION = exports.REQUEST_PASSWORD_RESET_ACTION = void 0;

/*
 *
 * RequestPasswordResetPage constants
 *
 */
var REQUEST_PASSWORD_RESET_ACTION = 'app/RequestPasswordResetPage/REQUEST_PASSWORD_RESET';
exports.REQUEST_PASSWORD_RESET_ACTION = REQUEST_PASSWORD_RESET_ACTION;
var REQUEST_PASSWORD_RESET_SUCCESS_ACTION = 'app/RequestPasswordResetPage/REQUEST_PASSWORD_RESET_SUCCESS';
exports.REQUEST_PASSWORD_RESET_SUCCESS_ACTION = REQUEST_PASSWORD_RESET_SUCCESS_ACTION;
var REQUEST_PASSWORD_RESET_FAILED_ACTION = 'app/RequestPasswordResetPage/REQUEST_PASSWORD_RESET_FAILED';
exports.REQUEST_PASSWORD_RESET_FAILED_ACTION = REQUEST_PASSWORD_RESET_FAILED_ACTION;
var DESTROY_PAGE_ACTION = 'app/RequestPasswordResetPage/DESTROY';
exports.DESTROY_PAGE_ACTION = DESTROY_PAGE_ACTION;