"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DESTROY_PAGE_ACTION = exports.RESET_PASSWORD_FAILED_ACTION = exports.RESET_PASSWORD_SUCCESS_ACTION = exports.RESET_PASSWORD_ACTION = void 0;

/*
 *
 * ResetPasswordPage constants
 *
 */
var RESET_PASSWORD_ACTION = 'app/ResetPasswordPage/RESET_PASSWORD';
exports.RESET_PASSWORD_ACTION = RESET_PASSWORD_ACTION;
var RESET_PASSWORD_SUCCESS_ACTION = 'app/ResetPasswordPage/RESET_PASSWORD_SUCCESS';
exports.RESET_PASSWORD_SUCCESS_ACTION = RESET_PASSWORD_SUCCESS_ACTION;
var RESET_PASSWORD_FAILED_ACTION = 'app/ResetPasswordPage/RESET_PASSWORD_FAILED';
exports.RESET_PASSWORD_FAILED_ACTION = RESET_PASSWORD_FAILED_ACTION;
var DESTROY_PAGE_ACTION = 'app/ResetPasswordPage/DESTROY';
exports.DESTROY_PAGE_ACTION = DESTROY_PAGE_ACTION;